# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7ed091cb6a2692ac40dbe6951701ea7e820b4f32b581e8635a47739d1b6cc99627b5cbfb17e171de13f5cc38457e1e19b2c0233a0dfb0cc5d1842fe0029695b

test:
  secret_key_base: 632f97be7ff462da87eb8b64b16806aef66eadf740c4befe3384c57480025685883bd998cc27910bc51b5dbfa42af98b0f66c879c96446d12f7406c3271ea968

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
